package com.diploma.ekg.controller;

import com.diploma.ekg.dto.CreateEKGRequest;
import com.diploma.ekg.entity.AutoGeneratedIdModel;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Collection;

@Controller
@RequestMapping("/ekg")
public class EKGController {

    //todo: decide on data format
    @PostMapping(path = "/save")
    @ResponseBody
    public void save(@RequestBody CreateEKGRequest request) {

    }

    //todo: service
    @GetMapping(path = "/{ekgId}")
    public Collection<? extends AutoGeneratedIdModel> getEkg(@PathVariable String ekgId) {
        return null;
    }

    @DeleteMapping(path = "/{ekgId}")
    public AutoGeneratedIdModel deleteEkg(@PathVariable String ekgId) {
        return null;
    }
}
