package com.diploma.ekg.entity;

import javax.persistence.*;

@Entity
@Table(name = "COMMENT")
public class Comment extends AutoGeneratedIdModel {

    @Column
    @Lob
    private String description;

    @OneToOne
    @JoinColumn(name = "PROJECT_ID")
    private Project project;

    @OneToOne
    @JoinColumn(name = "USER_ID")
    private User user;

    public Comment() {
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
