package com.diploma.ekg.entity;

import javax.persistence.*;

@Entity
@Table(name = "COMMENT")
public class Comment extends AutoGeneratedIdModel {

    @Column
    @Lob
    private String text;

    //    @Column
    @OneToOne
    @JoinColumn(name = "PROJECT_ID")
    private Project project;

    //    @Column
    @OneToOne
    @JoinColumn(name = "USER_ID")
    private User user;
}
