package com.diploma.ekg.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Lob;
import javax.persistence.Table;

@Entity
@Table(name = "DIAGNOSIS")
public class Diagnosis extends AutoGeneratedIdModel {

    @Column
    private String name;

    @Column
    @Lob
    private String description;

    public Diagnosis() {
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
