package com.diploma.ekg.entity;

import javax.persistence.*;

@Entity
@Table(name = "FULL_INTERVAL")
public class FullInterval extends AutoGeneratedIdModel {

    @Column
    private Float P;

    @Column
    private Float Q;

    @Column
    private Float R;

    @Column
    private Float S;

    @Column
    private Float T;

    @Column
    private Float U;

    @ManyToOne
    @JoinColumn(name = "LEAD_ID")
    private Lead lead;

    public FullInterval() {
    }

    public Float getP() {
        return P;
    }

    public void setP(Float p) {
        P = p;
    }

    public Float getQ() {
        return Q;
    }

    public void setQ(Float q) {
        Q = q;
    }

    public Float getR() {
        return R;
    }

    public void setR(Float r) {
        R = r;
    }

    public Float getS() {
        return S;
    }

    public void setS(Float s) {
        S = s;
    }

    public Float getT() {
        return T;
    }

    public void setT(Float t) {
        T = t;
    }

    public Float getU() {
        return U;
    }

    public void setU(Float u) {
        U = u;
    }

    public Lead getLead() {
        return lead;
    }

    public void setLead(Lead lead) {
        this.lead = lead;
    }
}
