package com.diploma.ekg.entity;

import com.diploma.ekg.dto.PatientDTO;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.util.Objects;

@Entity
@Table(name = "PATIENT")
public class Patient extends AutoGeneratedIdModel {

    @Column
    @NotNull
    private String firstName;

    @Column
    @NotNull
    private String lastName;

    @Column
    private String pesel;

    public Patient() {
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPesel() {
        return pesel;
    }

    public void setPesel(String pesel) {
        this.pesel = pesel;
    }

    public PatientDTO toDTO() {
        PatientDTO dto = new PatientDTO();
        dto.firstName = firstName;
        dto.lastName = lastName;
        dto.PESEL = pesel;
        return dto;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Patient patient = (Patient) o;
        return pesel.equals(patient.pesel);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pesel);
    }
}
