package com.diploma.ekg.entity;

import javax.persistence.*;

@Entity
@Table(name = "SMALL_INTERVAL")
public class SmallInterval extends AutoGeneratedIdModel {

    @Column
    private String intervalName;

    @Column
    private Float value;

    @ManyToOne
    @JoinColumn(name = "FULL_INTERVAL_ID")
    private FullInterval fullInterval;

    public SmallInterval() {
    }

    public String getIntervalName() {
        return intervalName;
    }

    public void setIntervalName(String intervalName) {
        this.intervalName = intervalName;
    }

    public Float getValue() {
        return value;
    }

    public void setValue(Float value) {
        this.value = value;
    }

    public FullInterval getFullInterval() {
        return fullInterval;
    }

    public void setFullInterval(FullInterval fullInterval) {
        this.fullInterval = fullInterval;
    }
}
