package com.diploma.ekg.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(name = "EKG_USER")
public class User extends AutoGeneratedIdModel {

    @Column(unique = true)
    private String email;

    @Column
    private String password;

    @Column
    private Boolean active;

    @Column
    private Boolean adminActive;

    public User() {
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean isActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public void setAdminActive(Boolean adminActive) {
        this.adminActive = adminActive;
    }
}
